"""Regenerate the recompile fixture corpus from real torch + tlparse runs.

This script is the **source of truth** for how every fixture in this directory
was produced. It writes (and overwrites) the fixtures in-place, so a fresh
clone of this repo with `pip install -e '.[dev]'` and `pip install tlparse`
should reproduce them byte-for-byte (up to timestamps and process ids that
the post-processing helpers below normalize away).

Why not commit only the outputs: when PyTorch's log format drifts across
minor versions, this script tells the next maintainer exactly how to refresh
the fixtures, and the diff of the regenerated outputs shows what changed.

Usage::

    cd /path/to/compile-lens
    python tests/fixtures/recompile/_generate.py

The fixtures produced:

- ``simple_batch_size.log``         — one model, one guard-failing dimension.
- ``mixed_guards.log``              — one model, three guard failure modes
                                       (size / dtype / stride) in one session.
- ``large_storm.log``               — tens of distinct shapes, each forcing a
                                       fresh recompile (``dynamic=False`` so
                                       dynamo does not auto-mark the dimension
                                       dynamic and stop recompiling). The perf
                                       benchmark inflates the count at runtime
                                       by iterating, so the committed fixture
                                       stays under the 500 KB pre-commit ceiling.
- ``tlparse_output/``               — directory produced by running ``tlparse``
                                       over the ``mixed_guards`` log dir.
- ``dynamo_explain_output.json``    — the structured object returned by
                                       ``torch._dynamo.explain`` for the
                                       same ``mixed_guards`` model.

Each ``<scenario>.log`` is paired with an ``<scenario>.expected.json`` that
captures what Tool 1's analyzer is *expected* to derive from the fixture.
The expected JSON is hand-authored (one entry per recompile cluster) and
not regenerated by this script — it is the ground-truth oracle the
analyzer tests will compare against.

Capture method: the ``.log`` fixtures are the ``[__recompiles]`` artifact
stream that ``TORCH_LOGS=recompiles`` writes to stderr — the exact text a
user sees when they enable the flag. We run each workload in a **subprocess**
with that env var set (the env var is read at torch-import time, so it must
be set before the child imports torch — an in-process ``set_logs`` after the
parent already imported torch does not produce the same artifact stream) and
keep only the lines carrying the ``[__recompiles]`` marker.
"""

from __future__ import annotations

import json
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

FIXTURE_DIR = Path(__file__).parent

#: Only lines carrying this marker are the recompiles artifact; everything else
#: on the child's stderr (e.g. an unrelated NumPy import warning) is dropped.
_RECOMPILES_MARKER = "[__recompiles]"


# ----------------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------------


def _capture_torch_logs(scenario: str) -> str:
    """Run the named workload in a subprocess under ``TORCH_LOGS=recompiles``
    and return the scrubbed ``[__recompiles]`` artifact stream from its stderr."""

    env = os.environ.copy()
    env["TORCH_LOGS"] = "recompiles"
    proc = subprocess.run(
        [sys.executable, str(Path(__file__).resolve()), "--workload", scenario],
        env=env,
        capture_output=True,
        text=True,
        check=True,
    )
    lines = [ln for ln in proc.stderr.splitlines() if _RECOMPILES_MARKER in ln]
    body = "\n".join(lines)
    return _scrub(body + "\n", scenario=scenario) if lines else ""


def _scrub(text: str, *, scenario: str) -> str:
    """Make the captured log deterministic across runs and machines.

    The ``recompiles`` artifact lines carry a glog-style prefix
    ``V<MMDD> <HH:MM:SS.ffffff> <pid> torch/_dynamo/guards.py:<lineno>]``. We
    normalize the date+time to ``<TS>`` and the pid to ``<PID>`` so the fixture
    diffs byte-clean across machines; the ``guards.py:<lineno>`` source ref is
    torch-version-specific but stable for a given version (regenerate on bump).
    The workload's own file path (where dynamo reports the recompiled function)
    is collapsed to ``<REPO>``. When PyTorch's *content* drifts, the diff is
    real; clock drift / pid churn does not show up.
    """

    # Collapse the leading glog prefix's volatile fields (date+time, pid).
    text = re.sub(
        r"V\d{4} \d{2}:\d{2}:\d{2}\.\d{6} \d+ ",
        "V<TS> <PID> ",
        text,
    )
    # Collapse the absolute path to the workload file (this generator) to <REPO>.
    text = text.replace(str(Path.cwd()), "<REPO>")
    return text


def _write(name: str, content: str) -> Path:
    path = FIXTURE_DIR / name
    path.write_text(content)
    print(f"  wrote {path.relative_to(Path.cwd())}  ({len(content):,} bytes)")
    return path


# ----------------------------------------------------------------------------
# Workloads — one per scenario
# ----------------------------------------------------------------------------


def _workload_simple_batch_size():
    """One ``@torch.compile``-d function called with two different batch sizes.

    Expected dynamo behaviour: compile on the first call, then a single
    guard failure ("tensor size at index 0") and one recompile on the second.
    """

    import torch  # noqa: PLC0415

    @torch.compile
    def f(x):
        return x * 2 + 1

    f(torch.randn(4, 16))
    f(torch.randn(8, 16))


def _workload_mixed_guards():
    """A model invoked so each call after the first breaks exactly one guard
    category — size, then dtype, then stride — to drive three distinct clusters.

    Each input is chosen to isolate its category against the first call's
    ``(8, 4)`` float32 contiguous tensor:

    - ``(16, 4)``            → size guard (dim 0: 8 → 16)
    - ``(8, 4)`` float64     → dtype guard (Float → Double), shape unchanged
    - ``(4, 8).t()``         → stride guard: ``.t()`` yields shape ``(8, 4)``
      (same as the first call) but non-contiguous, so size/dtype guards pass
      and only the stride/contiguity guard fails.
    """

    import torch  # noqa: PLC0415

    @torch.compile
    def f(x):
        return x.sum() + x.mean()

    f(torch.randn(8, 4))
    f(torch.randn(16, 4))  # size guard fails (dim 0)
    f(torch.randn(8, 4).to(torch.float64))  # dtype guard fails (Float -> Double)
    f(torch.randn(4, 8).t())  # stride guard fails (same shape, non-contiguous)


def _workload_large_storm():
    """A loop over many distinct input shapes, each forcing a fresh recompile.

    ``dynamic=False`` keeps dynamo from auto-marking the dimension dynamic
    after the first couple of recompiles (which would otherwise collapse the
    storm to ~2 recompiles); ``cache_size_limit`` is raised so every shape
    produces its own recompile rather than capping at the default.
    """

    import torch  # noqa: PLC0415

    torch._dynamo.config.cache_size_limit = 256

    @torch.compile(dynamic=False)
    def f(x):
        return x.relu().sum()

    for i in range(1, 51):
        f(torch.randn(i))


#: Scenario name -> workload. The subprocess entry point (``--workload <name>``)
#: looks the workload up here and runs it under the parent's ``TORCH_LOGS``.
_WORKLOADS = {
    "simple_batch_size": _workload_simple_batch_size,
    "mixed_guards": _workload_mixed_guards,
    "large_storm": _workload_large_storm,
}


# ----------------------------------------------------------------------------
# tlparse + dynamo.explain (single shared workload — mixed_guards)
# ----------------------------------------------------------------------------


def _emit_tlparse(out_dir: Path) -> None:
    """Capture a ``TORCH_TRACE``-style log of the ``mixed_guards`` workload,
    run the ``tlparse`` CLI over it, and commit *only* the parsed result.

    ``tlparse`` does not consume ``TORCH_LOGS=+recompiles`` stderr — it
    consumes ``TORCH_TRACE=<dir>`` output (a single ``dedicated_log_torch_trace_*.log``
    written by PyTorch into the directory named by the env var). The raw
    trace itself is large (~500 KB for our mixed_guards workload) and is
    not the format Mode B parses; we point the parser at the tlparse
    output instead.
    """

    import tempfile

    tlparse_bin = shutil.which("tlparse") or str(Path(sys.executable).parent / "tlparse")
    if not Path(tlparse_bin).exists():
        print("  ! tlparse not on PATH and not in venv bin — skipping fixture_tlparse")
        return

    with tempfile.TemporaryDirectory(prefix="cls_trace_") as trace_dir:
        env = os.environ.copy()
        env["TORCH_TRACE"] = trace_dir
        # Run the workload as a subprocess so TORCH_TRACE actually takes effect
        # (the env var is read at torch import time).
        runner = (
            "import torch\n"
            "@torch.compile\n"
            "def f(x):\n"
            "    return x.sum() + x.mean()\n"
            "f(torch.randn(8, 4))\n"
            "f(torch.randn(16, 4))\n"
            "f(torch.randn(16, 4).to(torch.float64))\n"
            "f(torch.randn(16, 8).t())\n"
        )
        subprocess.run([sys.executable, "-c", runner], env=env, check=True, capture_output=True)
        trace_files = list(Path(trace_dir).glob("dedicated_log_torch_trace_*.log"))
        if not trace_files:
            print("  ! TORCH_TRACE produced no log — skipping fixture_tlparse")
            return
        trace_file = trace_files[0]

        if out_dir.exists():
            shutil.rmtree(out_dir)
        out_dir.mkdir(parents=True)
        subprocess.run(
            [tlparse_bin, "--no-browser", "--overwrite", "-o", str(out_dir), str(trace_file)],
            check=True,
            capture_output=True,
        )

    # Mode B parses the structured-event outputs (raw.jsonl) and the index
    # (compile_directory.json). Everything else — raw.log (a copy of the
    # input TORCH_TRACE file, > 500 KB), index.html (visual report),
    # chromium_events.json (Chrome trace), and per-compile sub-dirs with FX
    # graphs and inductor HTML — is not Mode-B input and is dropped to keep
    # the fixture under the 500 KB-per-file pre-commit ceiling and small
    # enough to diff usefully.
    keep = {"raw.jsonl", "compile_directory.json"}
    for path in sorted(out_dir.rglob("*"), reverse=True):
        if path.is_dir():
            try:
                path.rmdir()  # only removes empty dirs
            except OSError:
                pass
            continue
        if path.name not in keep:
            path.unlink()

    # Scrub absolute paths so the fixture is identical across machines.
    home = str(Path.home())
    for path in sorted(out_dir.rglob("*")):
        if path.is_file():
            text = path.read_text()
            text = text.replace(home, "<HOME>")
            text = text.replace(str(Path.cwd()), "<REPO>")
            path.write_text(text)
            os.utime(path, (0, 0))

    n_files = sum(1 for _ in out_dir.rglob("*") if _.is_file())
    print(f"  wrote {out_dir.relative_to(Path.cwd())}/  ({n_files} files)")


def _emit_dynamo_explain() -> str:
    """Capture ``torch._dynamo.explain`` output for the mixed-guards model."""

    import torch  # noqa: PLC0415

    @torch.compile
    def f(x):
        return x.sum() + x.mean()

    explanation = torch._dynamo.explain(f)(torch.randn(8, 4))
    # ``explanation`` is an ExplainOutput dataclass with rich repr.  Serialize
    # the fields a Tool 1 collector cares about into JSON.
    payload = {
        "graph_count": explanation.graph_count,
        "graph_break_count": explanation.graph_break_count,
        "break_reasons": [str(reason) for reason in explanation.break_reasons],
        "ops_per_graph": [[str(op) for op in graph] for graph in explanation.ops_per_graph],
        "compile_times": getattr(explanation, "compile_times", None),
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


# ----------------------------------------------------------------------------
# Entry point
# ----------------------------------------------------------------------------


def main() -> int:
    # Subprocess entry point: run one workload under the parent's TORCH_LOGS and
    # let torch emit the recompiles artifact to stderr (which the parent captures).
    if "--workload" in sys.argv:
        name = sys.argv[sys.argv.index("--workload") + 1]
        _WORKLOADS[name]()
        return 0

    if "--dry-run" in sys.argv:
        print("dry-run: would regenerate fixtures in", FIXTURE_DIR)
        return 0

    try:
        import torch  # noqa: F401, PLC0415
    except ImportError:
        print("torch is not installed; install with: pip install torch", file=sys.stderr)
        return 1

    print("regenerating fixtures in", FIXTURE_DIR)

    _write("simple_batch_size.log", _capture_torch_logs("simple_batch_size"))
    _write("mixed_guards.log", _capture_torch_logs("mixed_guards"))
    _write("large_storm.log", _capture_torch_logs("large_storm"))

    # tlparse needs its own TORCH_TRACE run; it does not consume the
    # +recompiles stderr captured above. Failures here don't take down
    # the rest of the generator.
    try:
        _emit_tlparse(FIXTURE_DIR / "tlparse_output")
    except subprocess.CalledProcessError as exc:
        print(f"  ! tlparse pipeline exited {exc.returncode}; tlparse_output may be partial")

    explain = _emit_dynamo_explain()
    _write("dynamo_explain_output.json", explain)

    print("done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
