"""Regenerate the recompile fixture corpus from real torch + tlparse runs.

This script is the **source of truth** for how every fixture in this directory
was produced. It writes (and overwrites) the fixtures in-place, so a fresh
clone of this repo with `pip install -e '.[dev]'` and `pip install tlparse`
should reproduce them byte-for-byte (up to timestamps and process ids that
the post-processing helpers below normalize away).

Why not commit only the outputs: when PyTorch's log format drifts across
minor versions, this script tells the next maintainer exactly how to refresh
the fixtures, and the diff of the regenerated outputs shows what changed.

Usage::

    cd /path/to/compile-lens
    python tests/fixtures/recompile/_generate.py

The fixtures produced:

- ``simple_batch_size.log``         — one model, one guard-failing dimension.
- ``mixed_guards.log``              — one model, three guard failure modes
                                       (size / dtype / stride) in one session.
- ``large_storm.log``               — ~100 distinct shapes producing the
                                       full per-event content the perf
                                       benchmark needs as a unit. The
                                       benchmark inflates the count to
                                       ≥ 1000 at runtime by iterating, so
                                       the committed fixture stays under
                                       the 500 KB pre-commit ceiling.
- ``tlparse_output/``               — directory produced by running ``tlparse``
                                       over the ``mixed_guards`` log dir.
- ``dynamo_explain_output.json``    — the structured object returned by
                                       ``torch._dynamo.explain`` for the
                                       same ``mixed_guards`` model.

Each ``<scenario>.log`` is paired with an ``<scenario>.expected.json`` that
captures what Tool 1's analyzer is *expected* to derive from the fixture.
The expected JSON is hand-authored (one entry per recompile cluster) and
not regenerated by this script — it is the ground-truth oracle the
analyzer tests will compare against.
"""

from __future__ import annotations

import io
import json
import logging
import os
import re
import shutil
import subprocess
import sys
from pathlib import Path

FIXTURE_DIR = Path(__file__).parent


# ----------------------------------------------------------------------------
# Helpers
# ----------------------------------------------------------------------------


def _capture_torch_logs(workload, scenario: str) -> str:
    """Run ``workload()`` with ``TORCH_LOGS=+recompiles`` set, return the
    captured stderr (where torch emits the structured log lines)."""

    import torch  # noqa: PLC0415 — deferred so this module can be imported

    # for documentation purposes without torch installed.
    import torch._logging  # noqa: PLC0415

    # The structured logger goes to a real Logger named "torch._dynamo".
    # Replace its handlers with a single StringIO capture so we get a
    # deterministic copy of exactly what the user would see in stderr.
    buf = io.StringIO()
    handler = logging.StreamHandler(buf)
    handler.setFormatter(logging.Formatter("%(asctime)s [%(levelname)s] %(name)s: %(message)s"))

    # Mirror what TORCH_LOGS=+recompiles does internally.
    torch._logging.set_logs(recompiles=True)
    root = logging.getLogger("torch")
    saved_handlers = list(root.handlers)
    saved_level = root.level
    root.handlers[:] = [handler]
    root.setLevel(logging.DEBUG)
    try:
        # Reset dynamo state so repeated invocations of this script produce
        # the same compilation trace, not "already-cached" no-ops.
        torch._dynamo.reset()
        workload()
    finally:
        root.handlers[:] = saved_handlers
        root.setLevel(saved_level)
        torch._logging.set_logs()  # back to defaults

    return _scrub(buf.getvalue(), scenario=scenario)


def _scrub(text: str, *, scenario: str) -> str:
    """Make the captured log deterministic across runs and machines.

    Drops process ids, replaces absolute paths to the python tempdir with
    placeholders, normalizes ISO timestamps to ``<TS>``. The result is what
    we commit as a fixture — when PyTorch's *content* drifts, the diff is
    real; clock drift / pid churn does not show up.
    """

    # Normalize ISO timestamps that lead each line.
    text = re.sub(r"\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3}", "<TS>", text)
    # Normalize pid-like markers that appear in some torch.compile log lines.
    text = re.sub(r"pid=\d+", "pid=<PID>", text)
    # Normalize the python tempdir prefix so paths line up across machines.
    text = text.replace(str(Path.cwd()), "<REPO>")
    return text


def _write(name: str, content: str) -> Path:
    path = FIXTURE_DIR / name
    path.write_text(content)
    print(f"  wrote {path.relative_to(Path.cwd())}  ({len(content):,} bytes)")
    return path


# ----------------------------------------------------------------------------
# Workloads — one per scenario
# ----------------------------------------------------------------------------


def _workload_simple_batch_size():
    """One ``@torch.compile``-d function called with two different batch sizes.

    Expected dynamo behaviour: compile on the first call, then a single
    guard failure ("tensor size at index 0") and one recompile on the second.
    """

    import torch  # noqa: PLC0415

    @torch.compile
    def f(x):
        return x * 2 + 1

    f(torch.randn(4, 16))
    f(torch.randn(8, 16))


def _workload_mixed_guards():
    """A model invoked with three different argument shapes triggering three
    distinct guard categories: size, dtype, and stride (non-contiguous)."""

    import torch  # noqa: PLC0415

    @torch.compile
    def f(x):
        return x.sum() + x.mean()

    f(torch.randn(8, 4))
    f(torch.randn(16, 4))  # size guard fails
    f(torch.randn(16, 4).to(torch.float64))  # dtype guard fails
    f(torch.randn(16, 8).t())  # stride guard fails (non-contiguous)


def _workload_large_storm():
    """A loop that exercises ~100 distinct input shapes, each forcing a
    fresh recompile. ``torch._dynamo.config.cache_size_limit`` is raised so
    the loop produces the full 100 events rather than capping at the default.
    """

    import torch  # noqa: PLC0415

    torch._dynamo.config.cache_size_limit = 200

    @torch.compile
    def f(x):
        return x.relu().sum()

    for i in range(1, 101):
        f(torch.randn(i))


# ----------------------------------------------------------------------------
# tlparse + dynamo.explain (single shared workload — mixed_guards)
# ----------------------------------------------------------------------------


def _emit_tlparse(out_dir: Path) -> None:
    """Capture a ``TORCH_TRACE``-style log of the ``mixed_guards`` workload,
    run the ``tlparse`` CLI over it, and commit *only* the parsed result.

    ``tlparse`` does not consume ``TORCH_LOGS=+recompiles`` stderr — it
    consumes ``TORCH_TRACE=<dir>`` output (a single ``dedicated_log_torch_trace_*.log``
    written by PyTorch into the directory named by the env var). The raw
    trace itself is large (~500 KB for our mixed_guards workload) and is
    not the format Mode B parses; we point the parser at the tlparse
    output instead.
    """

    import tempfile

    tlparse_bin = shutil.which("tlparse") or str(Path(sys.executable).parent / "tlparse")
    if not Path(tlparse_bin).exists():
        print("  ! tlparse not on PATH and not in venv bin — skipping fixture_tlparse")
        return

    with tempfile.TemporaryDirectory(prefix="cls_trace_") as trace_dir:
        env = os.environ.copy()
        env["TORCH_TRACE"] = trace_dir
        # Run the workload as a subprocess so TORCH_TRACE actually takes effect
        # (the env var is read at torch import time).
        runner = (
            "import torch\n"
            "@torch.compile\n"
            "def f(x):\n"
            "    return x.sum() + x.mean()\n"
            "f(torch.randn(8, 4))\n"
            "f(torch.randn(16, 4))\n"
            "f(torch.randn(16, 4).to(torch.float64))\n"
            "f(torch.randn(16, 8).t())\n"
        )
        subprocess.run([sys.executable, "-c", runner], env=env, check=True, capture_output=True)
        trace_files = list(Path(trace_dir).glob("dedicated_log_torch_trace_*.log"))
        if not trace_files:
            print("  ! TORCH_TRACE produced no log — skipping fixture_tlparse")
            return
        trace_file = trace_files[0]

        if out_dir.exists():
            shutil.rmtree(out_dir)
        out_dir.mkdir(parents=True)
        subprocess.run(
            [tlparse_bin, "--no-browser", "--overwrite", "-o", str(out_dir), str(trace_file)],
            check=True,
            capture_output=True,
        )

    # Mode B parses the structured-event outputs (raw.jsonl) and the index
    # (compile_directory.json). Everything else — raw.log (a copy of the
    # input TORCH_TRACE file, > 500 KB), index.html (visual report),
    # chromium_events.json (Chrome trace), and per-compile sub-dirs with FX
    # graphs and inductor HTML — is not Mode-B input and is dropped to keep
    # the fixture under the 500 KB-per-file pre-commit ceiling and small
    # enough to diff usefully.
    keep = {"raw.jsonl", "compile_directory.json"}
    for path in sorted(out_dir.rglob("*"), reverse=True):
        if path.is_dir():
            try:
                path.rmdir()  # only removes empty dirs
            except OSError:
                pass
            continue
        if path.name not in keep:
            path.unlink()

    # Scrub absolute paths so the fixture is identical across machines.
    home = str(Path.home())
    for path in sorted(out_dir.rglob("*")):
        if path.is_file():
            text = path.read_text()
            text = text.replace(home, "<HOME>")
            text = text.replace(str(Path.cwd()), "<REPO>")
            path.write_text(text)
            os.utime(path, (0, 0))

    n_files = sum(1 for _ in out_dir.rglob("*") if _.is_file())
    print(f"  wrote {out_dir.relative_to(Path.cwd())}/  ({n_files} files)")


def _emit_dynamo_explain() -> str:
    """Capture ``torch._dynamo.explain`` output for the mixed-guards model."""

    import torch  # noqa: PLC0415

    @torch.compile
    def f(x):
        return x.sum() + x.mean()

    explanation = torch._dynamo.explain(f)(torch.randn(8, 4))
    # ``explanation`` is an ExplainOutput dataclass with rich repr.  Serialize
    # the fields a Tool 1 collector cares about into JSON.
    payload = {
        "graph_count": explanation.graph_count,
        "graph_break_count": explanation.graph_break_count,
        "break_reasons": [str(reason) for reason in explanation.break_reasons],
        "ops_per_graph": [[str(op) for op in graph] for graph in explanation.ops_per_graph],
        "compile_times": getattr(explanation, "compile_times", None),
    }
    return json.dumps(payload, indent=2, sort_keys=True) + "\n"


# ----------------------------------------------------------------------------
# Entry point
# ----------------------------------------------------------------------------


def main() -> int:
    if "--dry-run" in sys.argv:
        print("dry-run: would regenerate fixtures in", FIXTURE_DIR)
        return 0

    try:
        import torch  # noqa: F401, PLC0415
    except ImportError:
        print("torch is not installed; install with: pip install torch", file=sys.stderr)
        return 1

    print("regenerating fixtures in", FIXTURE_DIR)

    simple = _capture_torch_logs(_workload_simple_batch_size, "simple_batch_size")
    _write("simple_batch_size.log", simple)

    mixed = _capture_torch_logs(_workload_mixed_guards, "mixed_guards")
    _write("mixed_guards.log", mixed)

    storm = _capture_torch_logs(_workload_large_storm, "large_storm")
    _write("large_storm.log", storm)

    # tlparse needs its own TORCH_TRACE run; it does not consume the
    # +recompiles stderr captured above. Failures here don't take down
    # the rest of the generator.
    try:
        _emit_tlparse(FIXTURE_DIR / "tlparse_output")
    except subprocess.CalledProcessError as exc:
        print(f"  ! tlparse pipeline exited {exc.returncode}; tlparse_output may be partial")

    explain = _emit_dynamo_explain()
    _write("dynamo_explain_output.json", explain)

    print("done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
